version: 2
general:
  branches:
    only:
      - develop
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run: npm install
      - run:
          name: build
          command: npm build 
      - checkout
      - run:
          name: install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
      - run:
          name: aws configue
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set default.region "$AWS_DEFAULT_REGION"
            echo 'export PUBLIC_IP=$(curl ipinfo.io/ip)' >> $BASH_ENV
      - run:
          name: ingress rule
          command: echo "~/bin/aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID --protocol tcp --port 22 --cidr {$PUBLIC_IP}/32"
