version: 2
general:
  branches:
    only:
      - develop
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run: npm install
      - run:
          name: build
          command: npm build 
      - checkout
      - run:
          name: deploy
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
            PUBLIC_IP=$(curl ipinfo.io/ip)
            AWS_REGION=ap-southeast-1
            SG_ID=sg-084a022ccf9377168
            ~/bin/aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID \
              --protocol tcp --port 22 --cidr $PUBLIC_IP/24
