version: 2
general:
  branches:
    only:
      - develop
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run: npm install
      - run:
          name: build
          command: npm build 
      - checkout
      - run:
          name: install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
      - run:
          name: aws configue
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set default.region "$AWS_DEFAULT_REGION"
            echo 'export PUBLIC_IP=$(curl ipinfo.io/ip)' >> $BASH_ENV
      - run:
          name: ingress rule
          command: ~/bin/aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID --protocol tcp --port 22 --cidr $PUBLIC_IP/32
      - run:
          name: give ingress rule some time to propogate
          command: sleep 5
      - vonder-me.pem: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAhiu+i02qlIrJHQOJdI5e6F7Q1or8uLYYLQMYhnZzdtJLohDA
          iiYwMpFjicIrgfrxlB4C6W9cIM0EZjkcgFFBP3kgsZJ27/+ZKJbPCXTtlLo7F5cB
          qkqd3BcBfwqv7+Jpmj4WRRXUaJWXMDcjnzC9zfKzXRXHlFUX13wfm505P/NmwE2i
          bwSiUQFf4Gu00zGxv4FTA75j1KxZrK/y86h43YtpO66x0G6XH7ngMnMDdE9LT0hh
          ETQLsTGkMMVDfEe3lWgEIx+xxaPlx59ZbyP9/yjVpfViD3rTFjNin+YD31e5+JId
          Twq2CKN+FadwwbBL/eqgLWzCbkLv4Dj5ZjnR1wIDAQABAoIBADboR/4yNpC7izo4
          bFQqv2RRCR4DmxDsVFB3Z93/M5l4zkLwoBrpLehD33xM3gk/bQW0knR9gjJaNGax
          EJzio9UZ+OsyiUIGU+NsdCXmmCO5Yt1witnp11hugco/0WhWO+lHZ022dUqnjUvK
          BOXsyIAzxntdomNtv2gL/9NrMDafCYMGhum439vaemnb2UyJxLHPnDUEYLNAU1k5
          gwOps+BorZs08Vpsf4o/7wW/JCOFYW2eTwQessWJ2aTcXlEYmZAX3j5yEd9ekaAi
          iGP4lvKrQjFRahRxlpQoXXALDhHkwJLnZ4xqWOQHIfSY2PSnRMseMXzC9cXOcKrn
          29zqp2ECgYEAxMxpE9cLh/K5Ysi2+sPep5GGeSrRQgqyfYLu7TEOYNIiwehGSvrb
          lEx0ToH/c+2f4fXP67UvG477tVrED6YpUsWtOx1ioeWMbT7d9eYYDzV5zZncRV2N
          lrghJB0sTSFpCL3ir8gFCNR3pPjf2M6Cgv5tcClrilCklsvW6lQozg0CgYEArohW
          i5z6CtwtlZUH5FJqldkGg9If5UbHNTkrsklVfO90lbnIkqvm1iqE5fnGgkCIfx81
          rLxyX7HW8qDM06VVnZRE3JY/ots9EbA7hel7KatPJu4EAQjd5YdHL2zrcVvlbdgQ
          ufdoSMQ512WZ6jboqinhBhC27xt6eQ/fasXLynMCgYA/jv0IyVUSDRROkSB3kLbi
          S5+wlmGLAMVwv87GkCdiobtUAN5i7O3p0V9m05lbKY2PfsIuEBAsyFsG0U+s9i82
          al1uUClAvFBEIB+zgSKYFt9FxcFcLcDCwqkBbuKV7oprplgGCYWGuogBodc5wEhq
          Yh2aMeZnf3AIu8CnYZLkKQKBgFnPlplpQdHs0xgyBEmdj3NkplGXAwq8jS36KV4p
          FnCf1+JkI641/ycd4h1llpzYEGU57ijhIAnWPcHEtSID5jacYYMRXdWz84zynu6d
          4t7iZGyn9i+CHI1MO3lQFyfSHhGUKadIhMVNFGaexcEcWEWYH087sqcAANnjLRiI
          iAG5AoGBAMQrQ9zneMMFXm93ZQ0AXZv1mc3w4mnMPWrw3GVvMGihIHTKZ8k1l+jg
          QREmxoAGc4MFrb7IdQOUzFjcupw7+oNI8qRtCfcu56hEHKrmBJbs0kPdyyLJYSOl
          JFQu9jAIQ+cNvK4idGDxbJvqKYaIIH7cU3svv3bKbfcZSQlwfLGF
          -----END RSA PRIVATE KEY-----%
      - run:
          name: Deploy
          command: |
            echo {$EC2_USERNAME}
            echo {$EC2_PUBLIC_DNS}
            ssh -i $ssh_key $EC2_USERNAME@$EC2_PUBLIC_DNS
            npm start
