
version: 2
general:
  branches:
    only:
      - develop
jobs:
  build:
    docker:
      - image: 'cimg/node:14.17.0'
    steps:
      - checkout
      - run: npm install
      - run:
          name: build
          command: npm build 
      - checkout
      - run:
          name: install aws cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            chmod +x ./aws/install
            sudo ./aws/install
      - run:
          name: aws configue
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set default.region "$AWS_DEFAULT_REGION"
            echo 'export PUBLIC_IP=$(curl ipinfo.io/ip)' >> $BASH_ENV
      - run:
          name: ingress rule
          command: aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID --protocol tcp --port 22 --cidr $PUBLIC_IP/32
      - run:
          name: give ingress rule some time to propogate
          command: sleep 5
      - add_ssh_keys:
          fingerprints:
            - "07:9b:80:1a:f1:92:78:d8:c2:ca:78:7e:88:7c:b2:08"
      - run:
          name: Deploy
          command: |
            sudo ssh centos@54.255.147.111
